dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
script:
  - export CXX=g++-7
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=ON ..
  - make check
  - cd ..
  - bash <(curl -s https://codecov.io/bash)
